# Generated by Django 3.1.6 on 2021-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='img',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='no',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='sum',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
