# Generated by Django 3.1.6 on 2021-03-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
