# Generated by Django 3.1.6 on 2021-03-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210312_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='term',
        ),
    ]
