# Generated by Django 3.1.6 on 2021-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
