# Generated by Django 3.1.5 on 2021-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devlopment_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='assets/images')),
                ('fb', models.URLField()),
                ('twitter', models.URLField()),
                ('google', models.URLField()),
                ('pintrest', models.URLField()),
            ],
        ),
    ]
