# Generated by Django 3.1.5 on 2021-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlopment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devlopment_team',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devlopment_team',
            name='fb',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='devlopment_team',
            name='google',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='devlopment_team',
            name='pintrest',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='devlopment_team',
            name='twitter',
            field=models.CharField(max_length=200),
        ),
    ]
